---
driver:
  name: vagrant
  box_check_update: true
  # network:
  #   - ["forwarded_port", {guest: 80, host: 8977}]

provisioner:
  require_chef_omnibus: false
  install_strategy: skip
  log_level: warn
  #name: chef-solo
  #chef_solo_path: /usr/bin/chef-solo
  name: chef_zero
  chef_client_path: /usr/bin/chef-client
  data_bags_path: test/integration/data_bags

verifier:
  name: busser
  ruby_bindir: /usr/bin

platforms:
  - name: buster64
    driver:
      box: debian/buster64
      provider: libvirt
      provision: true
      vagrantfiles:
      - vagrant.rb
  - name: stretch64
    driver:
      box: debian/stretch64
      provider: libvirt
      provision: true
      vagrantfiles:
      - vagrant.rb
  - name: jessie64
    driver:
      box: debian/jessie64
      require_chef_omnibus: 12.3
      provider: libvirt
      provision: true
      vagrantfiles:
        - vagrant.rb

suites:
  - name: cernvm-fs
    run_list:
      - recipe[cernvm-fs::apt_repository]
      - recipe[cernvm-fs]
    attributes:
      cvmfs:
        client:
          default_local:
            http_proxy: 'http://proxy.gsi.de:3128/'
