---
language: ruby
cache: bundler

sudo: required
dist: xenial

services: docker

# bundler in the travis image is too old:
before_install:
  - gem install bundler

bundler_args: --without vagrant

before_script:
  - bundle exec kitchen list

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=12.3
    - CHEF_VERSION=12.14
    - CHEF_VERSION=13
    - CHEF_VERSION=14

rvm:
# - system # does not work with `gem install bundler`
  - 2.3
  - 2.5

matrix:
  exclude:
    - rvm: 2.3
      env: CHEF_VERSION=14

stages:
  - rubocop
  - foodcritic
  - test
  - kitchen

# this is the script for the test stage, where the matrix is expanded
script: bundle exec rake chefspec

jobs:
  fast_finish: true
  include:
    - stage: rubocop
      script: bundle exec rake rubocop
    - stage: foodcritic
      script: bundle exec rake foodcritic
    - stage: kitchen
      env: KITCHEN_PLATFORM=debian-stretch
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-jessie
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-buster
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=debian-wheezy
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=ubuntu-18.04
      script: bundle exec kitchen test $KITCHEN_PLATFORM
    - env: KITCHEN_PLATFORM=centos-7
      script: bundle exec kitchen test $KITCHEN_PLATFORM
  allow_failures:
    - rvm: 2.4
    - env: CHEF_VERSION=14
    - env: CHEF_VERSION=13
    - env: KITCHEN_PLATFORM=centos-7
    - stage: test
