#!/bin/bash
#
# Author:: Victor Penso
# Copyright:: 2013, GSI, HPC Department
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# check if there is only one input argument
if [ "$#" -eq "2" ]; then
  repo_name=$2
  case "$1" in
  publish)
    
    # Resign repository to make sure transaction works!
    
    ssh -qt $repo_name 'cvmfs_server resign'
    
    # Prepare repository for update
    
    ssh -qt $repo_name 'cvmfs_server transaction $repo_name' 

    # sync local data to the corresponding CVMFS server
    #   -v, --verbose               increase verbosity
    #   -t, --times preserve        modification times
    #   -z, --compress              compress file data during the transfer
    #   -r, --recursive             recurse into directories
    #   -l, --links                 copy symlinks as symlinks

    rsync -vtzrl --exclude-from /cvmfs/$repo_name.exclude --delete --delete-excluded /cvmfs/$repo_name $repo_name:/cvmfs/

    # Run publish on the CVMFS server as root, this needs to be 
    # allowed by sudo on the target machine!

    ssh -qt $repo_name 'cvmfs_server publish'

    # Show repository revisions
    ssh -qt $repo_name "cvmfs_server lstags $repo_name | cut -d'|' -f3,4"
    
    # SSH terminal allocation is needed to allow the command 
    # a user switch (su)

    ssh -qt $repo_name "df -h /cvmfs/$repo_name"

    ;;
  resign)
    ssh -qt $repo_name 'sudo cvmfs_server resign'
    ;;
  *)
    echo 'You can only publish or resign repositories!'
    ;;
  esac
else
  echo "Error: Parameters incomplete!"
  echo "   cvmfs [publish|resign] <REPO> "
fi  

